version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: classvault-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - backend-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    container_name: classvault-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - backend-network

  rabbitmq:
    image: rabbitmq:management
    container_name: classvault-rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mongodb-data:
